---
title: "alpha_estimation_1.0"
author: "andrew demetriou"
date: "11/25/2021"
---


```{r setup, include=FALSE}
library('data.table') # data manipulation
library('here')       # file logistics
library('corrplot')   # visualization
library('Hmisc')      # visualization
library("ggplot2")    # visualization
library('dplyr')      # data manipulation
library('psych')      # factor analysis and reliability
```

```{r}
# path with the actual data
data_file_path <- here("data")

# create a list with all of the files
data_files <- list.files(data_file_path)

# read in qualtrics data file
responses_dt <- fread(here(data_file_path, "annotation_number_estimation _2.2_November 28, 2021_07.51.csv"))

# remove junk on first two rows
responses_dt <- responses_dt[3:.N]

# read in prolific data file
demogs_dt <- fread(here(data_file_path, "prolific_export_619f3c47f6b78ee67274583e.csv"))
demogs_dt[, PROLIFIC_PID := participant_id]

# merge datasets
all_dt <- responses_dt[demogs_dt, on=.(PROLIFIC_PID)]
complete_dt <- responses_dt[demogs_dt, on=.(PROLIFIC_PID), nomatch=0]

# get question wording:
questions <- colnames(fread(here(data_file_path, data_files[1]), skip=1))
```

```{r}
#create a dataframe to work with
finished_dt <- all_dt[Finished=='True', ]

# 8 participants finished, and timed out
finished_timed_out_dt <- all_dt[status=='TIMED-OUT' & Finished=='True', ]

# 9 participants did not finish, and timed out - perhaps found in partial responses
unfinished_timed_out_dt <- all_dt[is.na(Finished) & status=='TIMED-OUT', ]
```

```{r}
#looking at the difference between Qualtrics time estimation and prolific
finished_dt$duration <- as.numeric(finished_dt$`Duration (in seconds)`)
finished_dt$time_diff <- finished_dt$time_taken - finished_dt$duration

#note columns to select
columns <- c("duration", "PROLIFIC_PID", "time_taken", "Sex", "age")

#plot duration by age, separated by sex
duration_plot <- finished_dt %>% select(columns) %>%
  ggplot(., aes(x=duration, y=age, color=Sex)) +
  geom_point()
duration_plot

#two observations took longer than 9000 seconds - responses look legit
#5fbc7c8b02bb0c14bfbe08ef
#5fd15934025b991384ef1116
finished_dt[duration > 9000,]

time_taken_plot <- finished_dt %>% select(columns) %>%
  ggplot(., aes(x=time_taken, y=age, color=Sex)) +
  geom_point()

#looks like it is returned after a very long time once it times out
finished_dt[time_taken > 7000,]
```


```{r}
#these had long stretches with the same value, but they look legit
suspicious_rows <- c(38, 72, 123, 132, 162, 176, 427, 479, 485)
suspicious_dt <- all_dt[suspicious_rows, ]


# this is the one that was revoked
all_dt[57, ]
```


```{r}
messages <- c("5f3e5e066dfaa70464615447", "61164fcd0209fe50694212f2", "55bb74f1fdf99b1519ef4762", "5fd15934025b991384ef1116", "5bf412a805d7260001f5247f", "5de7c6d448241d73d36ceaef", "5c6f1e080b99a000018cc53b", "5dde21012a30acd8ada645ec", "6158591c0aface73c971cd2b", "614ee4836d0150e0a1865e6e", "6155b46b4b82aa7811ffaabd")

#messages <- c("5bf412a805d7260001f5247f ")

messages_dt <- all_dt[all_dt$PROLIFIC_PID %in% messages]
```


```{r}
#names of lyric preferences columns for subsetting
lyric_column_names <- c(
  "Lyric_preferences_1","Lyric_preferences_2","Lyric_preferences_3",
  "Lyric_preferences_4","Lyric_preferences_5","Lyric_preferences_6",
  "Lyric_preferences_7", "Lyric_preferences_8", "Lyric_preferences_9", "Lyric_percentage_1")

#subset data table
lyrics_preferences_dt <- working_dt[, lyric_column_names, with=FALSE]

to_numbers <- function(x) {
  if(x ==  "Strongly disagree"){x = as.numeric(1)
  } else if (x== "Somewhat disagree"){x = as.numeric(2)
  } else if (x== "Neither agree nor disagree"){x = as.numeric(3)
  } else if (x=="Somewhat agree"){x = as.numeric(4)
  } else if (x=="Strongly agree"){x = as.numeric(5)
  } else {x = NA}
}

#execute recode function on relevant rows
lyrics_preferences_dt <- lyrics_preferences_dt[, .(
  L1 = lapply(Lyric_preferences_1, to_numbers), 
  L2 = lapply(Lyric_preferences_2, to_numbers), 
  L3 = lapply(Lyric_preferences_3, to_numbers),
  L4 = lapply(Lyric_preferences_4, to_numbers), 
  L5 = lapply(Lyric_preferences_5, to_numbers), 
  L6 = lapply(Lyric_preferences_6, to_numbers), 
  L7 = lapply(Lyric_preferences_7, to_numbers),
  L8 = lapply(Lyric_preferences_8, to_numbers),
  L9 = lapply(Lyric_preferences_9, to_numbers),
  L10 = Lyric_percentage_1)][, lapply(.SD, as.numeric)]

lyrics_preferences_dt$L2 <- 6-lyrics_preferences_dt$L2
```

```{r}
#extract actual wording of questions
lyrics_questions <- questions[20:28]
lyrics_questions <- gsub("Please indicate how much you agree with the following statements about your music preferences: - ", "", lyrics_questions)
lyrics_questions
```
```{r}
cor.mtest <- function(mat, ...) {
    mat <- as.matrix(mat)
    n <- ncol(mat)
    p.mat<- matrix(NA, n, n)
    diag(p.mat) <- 0
    for (i in 1:(n - 1)) {
        for (j in (i + 1):n) {
            tmp <- cor.test(mat[, i], mat[, j], ...)
            p.mat[i, j] <- p.mat[j, i] <- tmp$p.value
        }
    }
  colnames(p.mat) <- rownames(p.mat) <- colnames(mat)
  p.mat
}
```

```{r}
p.mat <- cor.mtest(corrplot_dt)
```
```{r}
corrplot_dt <- lyrics_preferences_dt[complete.cases(lyrics_preferences_dt),]
hist.data.frame(corrplot_dt)
```


```{r}
corrplot(cor(corrplot_dt), method = "color", type = 'lower', diag=FALSE, addCoef.col	
="black", p.mat = p.mat, sig.level=0.01)
```

```{r}
alpha(corrplot_dt)
fa(corrplot_dt)
```

