---
title: "intercepts"
author: "Andrew M. Demetriou"
date: "2/1/2022"
---

```{r, include=FALSE}
library("here")            # file logistics
library("tidyverse")       # data wrangling 
library("lme4")            # estimate random effects
library("tibble")          # data logistics
library("ggplot2")         # visualization
library("cowplot")         # visualization

# organize qualtrics output
source("data_file_re-shape_1.0.R")
```

read in participant data:

```{r}
data_file_path <- here("data")

# file name as a string
file_name <- "annotation_number_estimation _2.2_November 28, 2021_07.51.csv"

# read in qualtrics data file
responses_dt <- fread(here(data_file_path, file_name)) %>%
  data_file_reshape(., file_name)

responses_dt$item_ID <- as.integer(responses_dt$item_ID)

rm(data_file_path, file_name)
```

rename variables for ease of use with mplus:

```{r}
#the rdata function doesn't like my variable names; renaming:
colnames(responses_dt) <- c(
  #item and participant ID variables 
  "subject_ID", "item_ID",
  
  #participant ratings
  "y1", "y2", "y3", "y4", "y5", "y6", "y7", "y8", "y9", "y10")
```

```{r}
vars = names(responses_dt[,3:12]) 
data = responses_dt

models = lapply(setNames(vars, vars), function(var) {
  form = paste(var, "~ (1|item_ID) + (1|subject_ID)")
  lmer(form, data=data)
})

names(models) <- vars
```

```{r}
extract_intercepts <- function(model, parameter) {
  
  ranef <- ranef(model)
  
  if(parameter == "item_ID") {
    ranef <- ranef$item_ID
    ranef <- rownames_to_column(ranef, "item_ID")
    colnames(ranef) <- c("item_ID", "intercept")
    return(ranef)
    
  } else if (parameter == "subject_ID"){
    ranef <- ranef$subject_ID
    ranef <- rownames_to_column(ranef, "subject_ID")
    colnames(ranef) <- c("subject_ID", "intercept")
    return(ranef)
    
  } else {
    print("Error: paramter not recognized. Please enter either 'item_ID' or 'subject_ID'")
  }
     
}
```


```{r}
item_intercepts <- lapply(models, extract_intercepts, "item_ID")
subject_intercepts <- lapply(models, extract_intercepts, "subject_ID")
```

```{r}
plot_hist <- function(intercept_df) {
  intercept_df %>% ggplot(aes(intercept)) +
    geom_histogram(bins=50)
}
```

```{r}
item_plots <- lapply(item_intercepts, plot_hist)
subject_plots <- lapply(subject_intercepts, plot_hist)
plots <- c(item_plots, subject_plots)
```

```{r}
cowplot::plot_grid(plotlist = plots)
```

