---
title: "mPlus_model"
author: "Andrew M. Demetriou"
date: "16/12/2021"
---
```{r, include=FALSE}
library("here")            # file logistics
library("stringr")         # detect strings in raw output
library("tidyverse")       # data wrangling 
library("dplyr")           # data wrangling
library("texreg")          # output formatting
library("corrplot")        # visualization
library("MplusAutomation") # Mplus integration
library("MVN")             # testing multivariate normality
library("RVAideMemoire")   # multivariate q-q plot

#organize machine output
source("machines_as_fixed_reshape_1.0.R")
source("machines_as_subjects_reshape_1.0.R")

# organize qualtrics output
source("data_file_re-shape_1.0.R")
```

read in machine data:

```{r}
# path with data
data_file_path <- here("data/outputs")

# files
data_files <- list.files(data_file_path)
data_files <- data_files[1:44]

# build machine data frames
machines_as_fixed_dt <- organize_machine_outputs(data_files)
machines_as_fixed_dt$item_ID <- as.integer(machines_as_fixed_dt$item_ID)

#rm(machine_file_reshape, organize_machine_outputs, summarize_machine_run, gather_summarized_machine_runs)
```

read in participant data:

```{r}
data_file_path <- here("data")

# file name as a string
file_name <- "annotation_number_estimation _2.2_November 28, 2021_07.51.csv"

# read in qualtrics data file
participants_dt <- fread(here(data_file_path, file_name)) %>%
  data_file_reshape(., file_name)

participants_dt$item_ID <- as.integer(participants_dt$item_ID)

#rm(file_name, data_file_reshape)
```

```{r}
data_file_path <- here("data/outputs")

machines_as_participants_dt <- organize_machine_outputs_as_participants(data_files)
machines_as_participants_dt$ishuman <- 0
setnames(machines_as_participants_dt, "machine_ID", "participant_ID")
responses_dt <- participants_dt
responses_dt$ishuman <- 1
machines_as_participants_dt <- rbind(machines_as_participants_dt, responses_dt)

#between_list_check <- machines_as_participants_dt %>% select(item_ID, participant_ID, ishuman, everything()) %>% group_by(participant_ID) %>% summarize(t = mean(ishuman))


#rm(data_file_path, data_files, gather_summarized_machine_runs_as_participants, organize_machine_outputs_as_participants, machine_file_reshape_as_participants, summarize_machine_run_as_participants)
```

```{r}
machines_as_fixed_dt <- machines_as_fixed_dt %>% select(item_ID, sort(colnames(.[,2:81])))
```


```{r}
machines_as_fixed_dt <- merge(x=participants_dt, y=machines_as_fixed_dt, by="item_ID", all.x=TRUE)
```

```{r}
mvn(participants_dt[,3:12], multivariatePlot = "q-q")
RVAideMemoire::mqqnorm(participants_dt[,3:12], main = "Multi-normal Q-Q Plot")
```


format data for mplus:
```{r}
#format ID columns:
#sim$item_ID <- as.integer(sim$item_ID)
#sim$subject_ID <- as.integer(sim$subject_ID)
#prepareMplusData(sim, "Mplus/sim.dat")
```

```{r}
#the rdata function doesn't like my variable names; renaming:
colnames(machines_as_fixed_dt) <- c(
  #item and participant ID variables 
  "item_ID", "participant_ID",
  
  #participant ratings
  "y1", "y2", "y3", "y4", "y5", "y6", "y7", "y8", "y9", "y10", 
  
  #machine ratings, n_machines per value
  paste0("z", as.character(seq(length(colnames(machines_as_fixed_dt))-12))))
```

```{r}
#for variables that only appear in a between section, use
#correlation model`

model <- mplusObject(
  TITLE = "model;",
  MISSING = ".;",
  VARIABLE = "
  USEVARIABLES = item_ID participant_ID y1-y10 z1-z80;
  CLUSTER = item_ID participant_ID;
  BETWEEN = (item_ID) z1-z80;",
  
  ANALYSIS = "
  TYPE = CROSSCLASSIFIED RANDOM;
  ESTIMATOR = BAYES;
  FBITERATIONS = 5000;
  ALGORITHM = GIBBS(RW);
  PROCESSORS = 11;",
  
  MODEL = "
  
  %within% 
  y1-y10;
  
  %between item_ID% 
  y1-y10; [y1-y10];  
  y1 WITH y2-y10;
  y2 WITH y3-y10;
  y3 WITH y4-y10;
  y4 WITH y5-y10;
  y5 WITH y6-y10;
  y6 WITH y7-y10;
  y7 WITH y8-y10;
  y8 WITH y9-y10;
  y9 WITH y10;

  m1  BY   z1-z8;
  m2  BY  z9-z16;
  m3  BY z17-z24;
  m4  BY z25-z32;
  m5  BY z33-z40;
  m6  BY z41-z48;
  m7  BY z49-z56;
  m8  BY z57-z64;
  m9  BY z65-z72;
  m10 BY z73-z80;
  
  m1-m10@1;
 
  m1 WITH m2-m10;
  m2 WITH m3-m10;
  m3 WITH m4-m10;
  m4 WITH m5-m10;
  m5 WITH m6-m10;
  m6 WITH m7-m10;
  m7 WITH m8-m10;
  m8 WITH m9-m10;
  m9 WITH m10;
  
  m1  WITH y1;
  m2  WITH y2;
  m3  WITH y3;
  m4  WITH y4;
  m5  WITH y5;
  m6  WITH y6;
  m7  WITH y7;
  m8  WITH y8;
  m9  WITH y9;
  m10 WITH y10;

  %between participant_ID% 
  y1-y10; [y1-y10@0];", 
  
  OUTPUT = "Tech1 Tech8 standardized cinterval(hpd)",
  
  rdata = as.data.frame(machines_as_fixed_dt)
)

#fit <- mplusModeler(model, modelout = "sim.inp", run=1L)
#fit$results$errors
#fit$results$warnings
#readModels("sim.out")
```

```{r}
#start.time <- Sys.time()
fit <- mplusModeler(model, modelout = "sim.inp", run=1L)
#end.time <- Sys.time()
#time.taken_1 <- round(end.time - start.time, 2)
fit$results$errors
fit$results$warnings
```

```{r}
parameters <- data.frame(fit$results$parameters$stdyx.standardized)
DIC <- fit$results$summaries$DIC
results_correlations <- parameters[grep('.WITH', parameters$paramHeader), ]
results_variances <- parameters[grep('Variances', parameters$paramHeader), ]
#write.csv(parameters, "parameters.csv") 
```

```{r}
#the rdata function doesn't like my variable names; renaming:
colnames(machines_as_participants_dt) <- c(
  #item and participant ID variables 
  "participant_ID",  "item_ID", 
  
  #participant ratings
  "y1", "y2", "y3", "y4", "y5", "y6", "y7", "y8", "y9", "y10", 
  
  "ishuman")

machines_as_participants_dt <- as.data.frame(machines_as_participants_dt)
```

# estimate the difference between humans and machines per value

```{r}
model <- mplusObject(
  TITLE = "model;",
  MISSING = ".;",
  VARIABLE = "
  USEVARIABLES = participant_ID ishuman item_ID y1-y10;
  CLUSTER = participant_ID item_ID;
  BETWEEN = (item_ID) ishuman;",
  
  ANALYSIS = "
  TYPE = CROSSCLASSIFIED RANDOM;
  ESTIMATOR = BAYES;
  FBITERATIONS = 5000;
  ALGORITHM = GIBBS(RW);
  PROCESSORS = 11;",
  
  MODEL = "
  
  %within% 
  y1-y10;
  
  %between item_ID% 
  y1-y10; [y1-y10];  
  
  y1 WITH y2-y10;
  y2 WITH y3-y10;
  y3 WITH y4-y10;
  y4 WITH y5-y10;
  y5 WITH y6-y10;
  y6 WITH y7-y10;
  y7 WITH y8-y10;
  y8 WITH y9-y10;
  y9 WITH y10;
  
  y1-y10 ON ishuman;
  
  %between participant_ID% 
  y1-y10; [y1-y10@0];", 
  
  OUTPUT = "Tech1 Tech8 standardized cinterval(hpd)",
  
  rdata = machines_as_participants_dt
)
```

```{r}
#start.time <- Sys.time()
fit <- mplusModeler(model, modelout = "sim.inp", run=1L)
#end.time <- Sys.time()
#time.taken_1 <- round(end.time - start.time, 2)
fit$results$errors
fit$results$warnings

parameters <- data.frame(fit$results$parameters$stdyx.standardized)
DIC <- fit$results$summaries$DIC
```


# estimate the standard deviations of the subject, machine, and item intercepts

```{r}
# create two dataframes, one for machines and one for humans
machines <- machines_as_subjects %>% filter(group==0)
subjects <- machines_as_subjects %>% filter(group==1)

#create list of dataframes
data_frames <- makeNamedList(machines, subjects)

#run using lmer
descriptives <- list_of_dfs_results(data_frames)
```

```{r}
#the rdata function doesn't like my variable names; renaming:
colnames(machines_as_subjects) <- c(
  #item and participant ID variables
  #ishuman is a dummy var indicating 0 for machines, 1 for humans
  "item_ID", "ishuman", "subject_ID",

  #ratings
  "y1", "y2", "y3", "y4", "y5", "y6", "y7", "y8", "y9", "y10")
```

```{r}
# create two dataframes, one for machines and one for humans
machines_df <- machines_as_subjects %>% filter(ishuman==0)
subjects_df <- machines_as_subjects %>% filter(ishuman==1)
```

```{r}
#run null model using Mplus
model <- mplusObject(
  TITLE = "model;",
  MISSING = ".;",
  VARIABLE = "
  USEVARIABLES = subject_ID item_ID y1-y10;
  CLUSTER = subject_ID item_ID;",
  
  ANALYSIS = "
  TYPE = CROSSCLASSIFIED RANDOM;
  ESTIMATOR = BAYES;
  FBITERATIONS = 5000;
  ALGORITHM = GIBBS(RW);
  PROCESSORS = 10;",
  
  MODEL = "
  
  %within% 
  y1-y10;
  
  %between item_ID% 
  y1-y10; [y1-y10];  
  
  %between subject_ID% 
  y1-y10; [y1-y10@0];", 
  
  OUTPUT = "Tech1 Tech8 standardized cinterval(hpd)",
  
  rdata = machines_df
)
```

```{r}
start.time <- Sys.time()
fit <- mplusModeler(model, modelout = "sim.inp", run=1L)
end.time <- Sys.time()
time.taken_1 <- round(end.time - start.time, 2)
fit$results$errors
fit$results$warnings

parameters <- data.frame(fit$results$parameters$unstandardized)
DIC <- fit$results$summaries$DIC
```


