---
title: "machine_file_reshape"
author: "Andrew M. Demetriou"
date: "12/9/2021"
---

```{r}
library('here')            # file logistics
library('data.table')      # data manipulation
library("MplusAutomation") # Mplus integration
```

```{r}
# path with data
data_file_path <- here("data/outputs")

# files
data_files <- list.files(data_file_path)
```

Read in the raw file, and format data table:

```{r}
machine_file_reshape <- function(file){
  
  #read in data file
  machine_dt <- fread(here(data_file_path, file))
  
  #set column names to upper case
  setnames(machine_dt, toupper(names(machine_dt)))
  
  #set column names and order to match participant data set
  setnames(machine_dt, "SONG_ID", "item_ID")
  setnames(machine_dt, "SELF-DIRECTION", "SELF")
  
  #create machine ID column, and erase useless column
  machine_dt[, machine_ID := ..file][,V1:=NULL]

  #set column order to match participant order
  machine_dt <- machine_dt[, c("machine_ID", "item_ID", "ACHIEVEMENT", "BENEVOLENCE", "CONFORMITY", "HEDONISM", "POWER",  "SECURITY", "SELF", "STIMULATION",  "TRADITION", "UNIVERSALISM")]

  #names of values  
  value_names <- c("ACHIEVEMENT", "BENEVOLENCE", "CONFORMITY", "HEDONISM", "POWER",  "SECURITY", "SELF", "STIMULATION",  "TRADITION", "UNIVERSALISM")

  #pivot to wide format
  machine_dt <- dcast(machine_dt, item_ID ~ machine_ID, value.var = value_names) 
}
```

Make a list of formatted data tables from the raw files:

```{r}
#create list of data tables
list_of_machine_data_tables <- lapply(data_files[1:44], machine_file_reshape)

#name list
names(list_of_machine_data_tables) <- data_files[1:44]
```

Merge all data tables into one big table:

```{r}
#merge all datatables (wide format)
#big_ass_data_table <- setDT(unlist(list_of_machine_data_tables, recursive = FALSE), check.names = TRUE)
big_ass_data_table = Reduce(function(...) merge(..., all = TRUE), list_of_machine_data_tables)
```

Average multiple runs into single files:

```{r}
# make a list of strings to represent a series of runs
file_names <- lapply(seq(1,9,1), function(i){paste0("mxm_faruqui_", i, "_uniform_weight_lyrics.txt")})

# make a subset list of dataframes to represent the runs
t <- list_of_machine_data_tables[names(list_of_machine_data_tables) %in% file_names]

# make a single dataframe from the list
s <- rbindlist(t, use.names = FALSE, idcol = TRUE)
```

```{r}
#list header and tail variants
variant_list <- c("mxm_faruqi_", "mxm_split_")
weight_list  <- c("_idf_weight_lyrics.txt", "_uniform_weight_lyrics.txt")

#concatenate head, numbers 1-9, and tail
file_name_maker <- function(head, tail){
  lapply(seq(1,9,1), function(i){paste0(head, i, tail)})
}

#iterate over variant list with first weight 
list_1 <- lapply(variant_list, function(i){
  file_name_maker(head=i, tail=weight_list[1])
  })

#iterate over variant list with second weight 
list_2 <- lapply(variant_list, function(i){
  file_name_maker(head=i, tail=weight_list[2])
  })

#output list of character vectors
file_name_list <- append(list_1, list_2)  

#remove junk
rm(list_1, list_2, variant_list, weight_list, file_name_maker)
```

