---
title: "machine_file_reshape"
author: "Andrew M. Demetriou"
date: "12/9/2021"
---

```{r}
library('here')            # file logistics
library('data.table')      # data manipulation
library("MplusAutomation") # Mplus integration
library('dplyr')
```

```{r}
# path with data
data_file_path <- here("data/outputs")

# files
data_files <- list.files(data_file_path)
```

Read in the raw file, and format data table:

```{r}
machine_file_reshape <- function(file){
  
  #read in data file
  machine_dt <- fread(here(data_file_path, file))
  
  #set column names to upper case
  setnames(machine_dt, toupper(names(machine_dt)))
  
  #set column names and order to match participant data set
  setnames(machine_dt, "SONG_ID", "item_ID")
  setnames(machine_dt, "SELF-DIRECTION", "SELF")
  
  #create machine ID column, and erase useless column
  machine_dt[, machine_ID := ..file][,V1:=NULL]

  #set column order to match participant order
  machine_dt <- machine_dt[, c("machine_ID", "item_ID", "ACHIEVEMENT", "BENEVOLENCE", "CONFORMITY", "HEDONISM", "POWER",  "SECURITY", "SELF", "STIMULATION",  "TRADITION", "UNIVERSALISM")]

  #names of values  
  value_names <- c("ACHIEVEMENT", "BENEVOLENCE", "CONFORMITY", "HEDONISM", "POWER",  "SECURITY", "SELF", "STIMULATION",  "TRADITION", "UNIVERSALISM")

  #pivot to wide format
  machine_dt <- dcast(machine_dt, item_ID ~ machine_ID, value.var = value_names) 
}
```

Make a list of formatted data tables from the raw files:

```{r}
#create list of data tables
list_of_machine_data_tables <- lapply(data_files[1:44], machine_file_reshape)

#name list
names(list_of_machine_data_tables) <- data_files[1:44]
```

Merge all data tables into one big table:

```{r}
#merge all datatables (wide format)
#big_ass_data_table <- setDT(unlist(list_of_machine_data_tables, recursive = FALSE), check.names = TRUE)
big_ass_data_table = Reduce(function(...) merge(..., all = TRUE), list_of_machine_data_tables)
```

Average multiple runs into single files:

```{r}
# make a list of strings to represent a series of runs individually because I'm too fucking stupid to figure out how to put it in a function:
mxm_faruqi_uniform <- lapply(seq(1,9,1), function(i){paste0("mxm_faruqui_", i, "_uniform_weight_lyrics.txt")})
mxm_faruqi_idf <- lapply(seq(1,9,1), function(i){paste0("mxm_faruqui_", i, "_idf_weight_lyrics.txt")})
mxm_split_uniform <- lapply(seq(1,9,1), function(i){paste0("mxm_split_", i, "_uniform_weight_lyrics.txt")})
mxm_split_idf <- lapply(seq(1,9,1), function(i){paste0("mxm_split_", i, "_idf_weight_lyrics.txt")})

# create a list of file lists
file_names <- list(mxm_faruqi_uniform, mxm_faruqi_idf, mxm_split_uniform, mxm_split_idf)
# name the elements in the list after the machine setup used to run
names(file_names) <- c("mxm_faruqi_uniform", "mxm_faruqi_idf", "mxm_split_uniform", "mxm_split_idf")

values <- c("ACHIEVEMENT", "BENEVOLENCE", "CONFORMITY", "HEDONISM", "POWER", "SECURITY", "SELF", "STIMULATION", "TRADITION", "UNIVERSALISM")
```

```{r}
# make a subset list of dataframes to represent the runs
t <- list_of_machine_data_tables[names(list_of_machine_data_tables) %in% file_names[[1]]]

# make a single dataframe from the list
s <- rbindlist(t, use.names = FALSE, idcol = TRUE)

# compute means by item
u <- s %>% group_by(item_ID) %>% summarize(
  ACHIEVEMENT_mxm_faruqui_uniform = mean(ACHIEVEMENT_mxm_faruqui_1_uniform_weight_lyrics.txt),
  BENEVOLENCE_mxm_faruqui_uniform = mean(BENEVOLENCE_mxm_faruqui_1_uniform_weight_lyrics.txt),                                                  
  CONFORMITY_mxm_faruqui_uniform = mean(CONFORMITY_mxm_faruqui_1_uniform_weight_lyrics.txt),
  HEDONISM_mxm_faruqui_uniform = mean(HEDONISM_mxm_faruqui_1_uniform_weight_lyrics.txt),
  POWER_mxm_faruqui_uniform = mean(POWER_mxm_faruqui_1_uniform_weight_lyrics.txt),
  SECURITY_mxm_faruqui_uniform = mean(SECURITY_mxm_faruqui_1_uniform_weight_lyrics.txt),
  SELF_mxm_faruqui_uniform = mean(SELF_mxm_faruqui_1_uniform_weight_lyrics.txt),
  STIMULATION_mxm_faruqui_uniform = mean(STIMULATION_mxm_faruqui_1_uniform_weight_lyrics.txt),
  TRADITION_mxm_faruqui_uniform = mean(TRADITION_mxm_faruqui_1_uniform_weight_lyrics.txt),
  UNIVERSALISM_mxm_faruqui_uniform = mean(UNIVERSALISM_mxm_faruqui_1_uniform_weight_lyrics.txt)
)
```

```{r}
t <- list_of_machine_data_tables[names(list_of_machine_data_tables) %in% file_names[[1]]] %>%
  rbindlist(., use.names = FALSE, idcol = TRUE)

#paste0(values[1], "_", names(file_names[1]))
file_name <- file_names[1]

r <- lapply(values, function(i){
  paste0(i, "_", names(file_name))
})

colnames(s) <- c("trial", "item_ID", r[[1]], r[[2]], r[[3]], r[[4]], r[[5]], r[[6]], r[[7]], r[[8]], r[[9]], r[[10]])
```

```{r}

```


```{r}
summarize_machine_run  <- function(list_of_machine_data_tables, file_names){

  ##extract working data.table from list of data tables

  #select data tables by file name
  data_table <- list_of_machine_data_tables[names(list_of_machine_data_tables) %in% file_names]%>%
    # bind data tables into a single data table
    rbindlist(., use.names=FALSE, idcol=TRUE)

  #list of schwartz values
  values <- c("ACHIEVEMENT", "BENEVOLENCE", "CONFORMITY", "HEDONISM", "POWER", "SECURITY", "SELF", "STIMULATION", "TRADITION", "UNIVERSALISM")


  #make list of column names
  values_by_machine_setup <- lapply(values, function(i){
  paste0(i, "_", names(file_name))
  })
  
  colnames(data_table) <- c(
    "trial", "item_ID", 
    values_by_machine_setup[[1]], values_by_machine_setup[[2]], values_by_machine_setup[[3]], values_by_machine_setup[[4]], 
    values_by_machine_setup[[5]], values_by_machine_setup[[6]], values_by_machine_setup[[7]], values_by_machine_setup[[8]],
    values_by_machine_setup[[9]], values_by_machine_setup[[10]])
  
}
```

